version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes: 
      - db:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  # NOT USED   
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local